theme: minima
name: Bytesize Architecture Sessions
title: Info site for Bytesize Architecture Sessions
description: An site to gather knowledge what are and how to run Bytesize Architecture Sessions
url: https://bytesizearchitecturesessions.com/
include: ["_pages"]
header_pages:
  - about.md
 
